name: flame_audio
publish_to: none
description: |
  Audio support for the Flame game engine, basically a thin wrapper around the audioplayers package.
version: 2.11.8
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_audio
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - audio

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  audioplayers:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_audioplayers.git
      ref: br_audioplayers-v6.1.0_ohos
      path: packages/audioplayers
  flame: ^1.30.1
  flutter:
    sdk: flutter
  synchronized: ^3.1.0

dev_dependencies:
  dartdoc: ^8.0.8
  flame_lint: ^1.4.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
